# This is a basic workflow to help you get started with Actions

nimi :velocity
# Hallitsee, milloin toiminto suoritetaan. Käynnistää työnkulun push- tai pull-pyynnössä
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      suorita : # Käytä tätä yameä työnktiedostossa jokaisessa työssä
käynnissä : itse isännöityö
        echo Lisää muita rakennettavia toimintoja,
        kaikutesti ja ota projekti käyttöön.
